import { exportDocument } from '../utils/history';

export function useAppViewProps({
  view,
  currentProjectId,
  user,
  goHome,
  goBackToProject,
  signOut,
  headerRef,
  projects,
  openProject,
  handleDeleteProject,
  formatDate,
  setShowCreateProject,
  currentProject,
  currentBatchSession,
  currentBatchDisplayState,
  provider,
  setProvider,
  apiKey,
  setApiKey,
  showApiKey,
  setShowApiKey,
  inputTab,
  setInputTab,
  isDragging,
  setIsDragging,
  projectFileInputRef,
  projectDocxInputRef,
  projectImportRef,
  handleProjectDocumentDrop,
  handleProjectDocumentFiles,
  handleProjectDocxFiles,
  files,
  docxFiles,
  removeFile,
  removeDocxFile,
  pastedText,
  setPastedText,
  requestPauseActiveBatch,
  handleResetProjectBatchSession,
  getBatchStatusTitle,
  getBatchResumeText,
  getBatchSourceSelectionHint,
  warningMessage,
  error,
  handleProjectRecognize,
  projectDocs,
  projectSummaryDoc,
  openDocFromProject,
  formatDocumentPageProgress,
  handleRemoveDocFromProject,
  handleBuildSummary,
  handleDeleteSummary,
  handleProjectImport,
  handleProjectTitleChange,
  progress,
  activeBatchUiState,
  setView,
  handlePdClick,
  pdWidth,
  setPdPanelRef,
  startResize,
  privatePersons,
  profPersons,
  pdTypeGroups,
  pdTypeLabels,
  anonymized,
  pdInDoc,
  initNavCounter,
  navigateToPd,
  openPdEditor,
  handleDeletePdEntry,
  anonymizeAllByCategory,
  pdNavState,
  docTitle,
  setDocTitle,
  titleRowRef,
  handleToggleOriginalViewer,
  handleLoadOriginalViewerImages,
  triggerExport,
  showLongDocWarning,
  setShowLongDocWarning,
  editorHtml,
  handleEditorHtmlChange,
  personalData,
  editorDomRef,
  highlightUncertain,
  editorTotalPages,
  editorCurrentPage,
  editorPageInput,
  editorPageInputRef,
  setEditorPageInput,
  handleEditorPageSubmit,
  handleEditorPageStep,
  handleRemovePdMark,
  handleApplyPdCanonicalText,
  openPdFragmentEditor,
  handleAttachPdMark,
  handleAddPdMark,
  handleRemoveAmbiguousMark,
  handleUncertainResolved,
  originalPage,
  setOriginalPage,
  zoomActive,
  setZoomActive,
  zoomScale,
  setZoomScale,
  viewerWidth,
  showOriginal,
  originalImages,
  hasPD,
  onCloseOriginal,
  showUncertainWarning,
  uncertainCount,
  separatorCount,
  handleUncertainProceed,
  handleUncertainCancel,
  savedMsg,
  showUnsaved,
  handleUnsavedSave,
  handleUnsavedDiscard,
  setShowUnsaved,
  currentEditingPd,
  setEditingPdId,
  handleSavePdEdit,
  currentEditingPdFragment,
  setEditingPdFragment,
  handleSavePdFragmentEdit,
  showCreateProject,
  newProjectTitle,
  setNewProjectTitle,
  handleCreateProject,
  showRebuildConfirm,
  handleConfirmRebuild,
  setShowRebuildConfirm,
} = {}) {
  const homeProps = {
    projects,
    onCreateProject: () => setShowCreateProject(true),
    onOpenProject: openProject,
    onDeleteProject: handleDeleteProject,
    formatDate,
  };

  const projectProps = {
    currentProject,
    currentBatchSession,
    currentBatchDisplayState,
    provider,
    setProvider,
    apiKey,
    setApiKey,
    showApiKey,
    setShowApiKey,
    inputTab,
    setInputTab,
    isDragging,
    setIsDragging,
    projectFileInputRef,
    projectDocxInputRef,
    projectImportRef,
    handleProjectDocumentDrop,
    handleProjectDocumentFiles,
    handleProjectDocxFiles,
    files,
    docxFiles,
    removeFile,
    removeDocxFile,
    pastedText,
    setPastedText,
    requestPauseActiveBatch,
    handleResetProjectBatchSession,
    getBatchStatusTitle,
    getBatchResumeText,
    getBatchSourceSelectionHint,
    warningMessage,
    error,
    handleProjectRecognize,
    formatDate,
    projectDocs,
    projectSummaryDoc,
    openDocFromProject,
    formatDocumentPageProgress,
    handleRemoveDocFromProject,
    exportDocument,
    handleBuildSummary,
    handleDeleteSummary,
    handleProjectImport,
    onImportClick: () => projectImportRef.current?.click(),
    onProjectTitleChange: handleProjectTitleChange,
  };

  const processingProps = {
    progress,
    activeBatchUiState,
    onPause: () => requestPauseActiveBatch('project'),
    onResume: handleProjectRecognize,
    onReturnToProject: () => setView('project'),
  };

  const resultProps = {
    showOriginal,
    originalImages,
    hasPD,
    pdWidth,
    setPdPanelRef,
    startResize,
    privatePersons,
    profPersons,
    pdTypeGroups,
    pdTypeLabels,
    anonymized,
    pdInDoc,
    handlePdClick,
    initNavCounter,
    navigateToPd,
    openPdEditor,
    handleDeletePdEntry,
    anonymizeAllByCategory,
    pdNavState,
    docTitle,
    setDocTitle,
    titleRowRef,
    handleToggleOriginalViewer,
    handleLoadOriginalViewerImages,
    triggerExport,
    showLongDocWarning,
    setShowLongDocWarning,
    editorHtml,
    handleEditorHtmlChange,
    personalData,
    editorDomRef,
    highlightUncertain,
    editorTotalPages,
    editorCurrentPage,
    editorPageInput,
    editorPageInputRef,
    setEditorPageInput,
    handleEditorPageSubmit,
    handleEditorPageStep,
    handlePdClickFromEditor: handlePdClick,
    handleRemovePdMark,
    handleApplyPdCanonicalText,
    openPdFragmentEditor,
    handleAttachPdMark,
    handleAddPdMark,
    handleRemoveAmbiguousMark,
    handleUncertainResolved,
    originalPage,
    setOriginalPage,
    zoomActive,
    setZoomActive,
    zoomScale,
    setZoomScale,
    viewerWidth,
    onCloseOriginal,
  };

  return {
    headerProps: {
      view,
      currentProjectId,
      user,
      onGoHome: goHome,
      onGoBackToProject: goBackToProject,
      onSignOut: () => signOut(),
      headerRef,
    },
    overlayProps: {
      showUncertainWarning,
      uncertainCount,
      separatorCount,
      onUncertainProceed: handleUncertainProceed,
      onUncertainCancel: handleUncertainCancel,
      savedMsg,
      showUnsaved,
      docTitle,
      onUnsavedSave: handleUnsavedSave,
      onUnsavedDiscard: handleUnsavedDiscard,
      onUnsavedClose: () => setShowUnsaved(false),
      currentEditingPd,
      onClosePdEditor: () => setEditingPdId(null),
      onSavePdEdit: handleSavePdEdit,
      currentEditingPdFragment,
      onClosePdFragmentEditor: () => setEditingPdFragment(null),
      onSavePdFragmentEdit: handleSavePdFragmentEdit,
      showCreateProject,
      newProjectTitle,
      setNewProjectTitle,
      onCreateProject: handleCreateProject,
      onCloseCreateProject: () => {
        setShowCreateProject(false);
        setNewProjectTitle('');
      },
      showRebuildConfirm,
      onConfirmRebuild: handleConfirmRebuild,
      onCloseRebuildConfirm: () => setShowRebuildConfirm(false),
    },
    mainProps: {
      view,
      viewHome: 'home',
      viewProcessing: 'processing',
      viewProject: 'project',
      viewResult: 'result',
      homeProps,
      projectProps,
      processingProps,
      resultProps,
    },
  };
}
